### ISSUE TITLE
hirise_assembly.py uses unknown package "bamtags"

### ISSUE THREAD

**Issue by bagavi** [DovetailGenomics/HiRise_July2015_GR#2]
The script "hisrise_assemply.py" imports the package "bamtags", which is neither a part of the software nor a part of the standard python libraries.

Because of this issue, the code exits with an error.  How to overcome this issue?

**Comment by ViriatoII** [comment]
I am also having this problem. 

I don't even find information about this module on google. It would be nice to have some kind of feedback. There are barely any comments on the scripts and this Forum is a desert.

**Comment by ViriatoII** [comment]
Ok, for anyone with the same problem:
 bamtags.py is provided in this github, it's in the scripts section. 

The main page says you must add the scripts directory to the PATH variable. Somehow this function was not on my PATH, even though the others were. Redoing this corrected the issue. However, it gives an error message about tags not being present:

>Traceback (most recent call last):
  File "/opt/share/software/packages/HiRise_July2015_GR/scripts/bamtags.py", line 15, in mate_mapq
    return line.opt("xm")
  File "pysam/calignmentfile.pyx", line 3689, in pysam.calignmentfile.AlignedSegment.opt (pysam/calignmentfile.c:40141)
  File "pysam/calignmentfile.pyx", line 3404, in pysam.calignmentfile.AlignedSegment.get_tag (pysam/calignmentfile.c:35280)
KeyError: "tag 'xm' not present"

>During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/share/software/packages/HiRise_July2015_GR/scripts/pair_sep_histogram.py", line 114, in <module>
    if BamTags.mate_mapq(aln) < args.min_qual: continue
  File "/opt/share/software/packages/HiRise_July2015_GR/scripts/bamtags.py", line 17, in mate_mapq
    return line.opt("MQ")
  File "pysam/calignmentfile.pyx", line 3689, in pysam.calignmentfile.AlignedSegment.opt (pysam/calignmentfile.c:40141)
  File "pysam/calignmentfile.pyx", line 3404, in pysam.calignmentfile.AlignedSegment.get_tag (pysam/calignmentfile.c:35280)
KeyError: "tag 'MQ' not present"
