### ISSUE TITLE
Model_fit.py fails due to nn_estimate being 0

### ISSUE THREAD

**Issue by ViriatoII** [DovetailGenomics/HiRise_July2015_GR#3]
Hello,
 
This seems like a great pipeline, but I can't get it to work. One of the initial functions (model_fit.py) fails. 
It is run in HiRise_commands here:
>cat all_smoothed_corrected.merged_histogram | model_fit.py -m 1000 -P nn_estimate.txt -o datamodel.out > datamodel.out.out

nn_estimate.txt contains the following information: {'G': 338789346.0, 'Nn': 0.0}. Is the value of 'Nn' the problem here? This estimate is calculated by estimate_Pn_bam.py

>#!/usr/bin/env python3
...
from past.utils import old_div
...
Traceback (most recent call last):
  File "/opt/share/software/packages/HiRise_July2015_GR/scripts/model_fit.py", line 155, in <module>
    pn=old_div(1.0,(1.0+old_div(model['l'],(model['nu']*G))))
  File "/opt/share/software/packages/HiRise_July2015_GR/pyvirt/lib/python3.5/site-packages/past/utils/__init__.py", line 95, in old_div
    return a / b
ZeroDivisionError: float division by zero

**Comment by ViriatoII** [comment]
So I've checked that all processes previous to model_fit.py run smoothly and output files such as:
- assembly0
- raw_chunks/*.deep_regions.bed
- contiguity_correction
- chicago_link_density_threshold.txt (this one is also 0, but is not cause of error so far)

Thus I believe I got the input data correct.

  model_fit.py also runs if the nn_estimate is > 0. So is the nn_estimate wrongly calculated? Why?

**Comment by ViriatoII** [comment]
Here's my whole workflow, to see if I created the input data right.

>Ctgs=/biodata/pipeline/Canu/ERR1725394/AAlpina.contigs.fasta` # Canu assembly contigs (from PacBio reads)
read1=/biodata/pipeline/data/ERR1725392_1.fastq              # HiC reads R1
read2=/biodata/pipeline/data/ERR1725392_2.fastq              # HiC reads R2
sread1=/biodata/pipeline/data/ERR1775131_1.fastq             # short reads R1
sread2=/biodata/pipeline/data/ERR1775131_2.fastq             # short reads R2
mkdir HiCMap shortMap

sort and index BAM files, created from R1 and R2 Chicago reads that were aligned against assembly contigs (Canu assembler). These BAMs are tagged with samblaster --addMateTags

>cd HiCMap
  bwa aln $Ctgs $read1 -f reads1_1.sai -t 20 # Align to assembly
  bwa aln $Ctgs $read2 -f reads1_2.sai -t 20 
  bwa sampe -a 300000 $Ctgs reads1_1.sai reads1_2.sai $read1 $read2 | samblaster --addMateTags | samtools view -bS -o reads.bam  
  samtools sort reads.bam -o reads.srt.bam
  samtools rmdup reads.srt.bam reads.srt.rmdup.bam
  samtools index reads.srt.rmdup.bam &

same procedure to short reads, to create "SHOTGUN_BAMS" input of hirise.
>cd ../shortMap
  bwa aln $Ctgs $sread1 -f reads2_1.sai -t 20
  bwa aln $Ctgs $sread2 -f reads2_2.sai -t 20
  bwa sampe -a 300000 $Ctgs reads2_1.sai reads2_2.sai $sread1 $sread2 | samblaster --addMateTags | samtools view -bS -o reads.bam 
  samtools sort reads.bam -o reads.srt.bam
  samtools rmdup reads.srt.bam reads.srt.rmdup.bam
  samtools index reads.srt.rmdup.bam  

 run HiRise scaffolding 
>cd ../scaffolding
bash hirise_commands.pa.bash ../HiCMap/reads.srt.rmdup.bam $Ctgs ../shortMap/reads.srt.rmdup.bam 10 30
